import { Roboto } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const roboto = Roboto({  weight: '500', subsets: ["latin"] });

export const metadata = {
  title: "Finapp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      fallbackRedirectUrl={process.env.NEXT_PUBLIC_CLERK_FALLBACK_REDIRECT_URL}
      signInUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL}
      signUpUrl={process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL}
    >
      <html lang="en">
        <head>
          <style>{`body { font-family: ${roboto.style.fontFamily}; }`}</style>
        </head>
        <body className={roboto.className}>
          <Toaster />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
